---
- name: register rhel 
  redhat_subscription:
    state: present
    username: paulo.luizetto@smanager.com.br 
    password: '@123Padrao'
    pool_ids: 8a85f99c69d235390169ed7add29150a 

- name: Add repositories
  yum_repository:
    name: "{{ item }}" 
    enabled: yes
  loop:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
...

